### ISSUE TITLE
Install and configure himawaripy

### ISSUE THREAD

**Issue by Notgnoshi** [Notgnoshi/dotfiles#56]
https://github.com/boramalper/himawaripy

Use
```
ExecStart=bash -c "/home/nots/.local/bin/himawaripy --auto-offset --level 4"
```

**Comment by Notgnoshi** [comment]
```bash
pip install himawaripy
mkdir -p .config/systemd/user
cd .config/systemd/user
wget https://raw.githubusercontent.com/boramalper/himawaripy/master/systemd/himawaripy.service
wget https://raw.githubusercontent.com/boramalper/himawaripy/master/systemd/himawaripy.timer
himawaripy --auto-offset --save-battery --level 4
# Edit to use absolute path, remove --save-battery if necessary
vim himawaripy.service
systemctl --user enable --now himawaripy.timer

# Helpful for debugging:
systemctl --user status himawaripy.timer
systemctl --user status himawaripy.service
systemctl --user start himawaripy.service
```

**Comment by Notgnoshi** [comment]
```
nots@pandemonium ~/.config/systemd/user $ himawaripy --auto-offset --level 4
himawaripy 2.2.0
Updating...
Latest version: 2022/05/07 15:00:00 GMT.
Detected offset: UTC-05:00
Offset version: 2022/05/07 00:00:00 GMT.
Downloading tiles...
Downloading tiles: 1/16 completed...
Downloading tiles: 2/16 completed...
Downloading tiles: 3/16 completed...
Downloading tiles: 4/16 completed...
Downloading tiles: 5/16 completed...
Downloading tiles: 6/16 completed...
Downloading tiles: 7/16 completed...
Downloading tiles: 8/16 completed...
Downloading tiles: 9/16 completed...
Downloading tiles: 10/16 completed...
Downloading tiles: 11/16 completed...
Downloading tiles: 12/16 completed...
Downloading tiles: 13/16 completed...
Downloading tiles: 14/16 completed...
Downloading tiles: 15/16 completed...
Downloading tiles: completed.
Saving to '/home/nots/.cache/himawaripy/himawari-20220507T000000.png'...
No such key “draw-background”
No such key “draw-background”
Exception in thread himawaripy-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nots/.local/lib/python3.10/site-packages/himawaripy/__main__.py", line 214, in thread_main
    r = set_background(output_file)
  File "/home/nots/.local/lib/python3.10/site-packages/himawaripy/utils.py", line 36, in set_background
    assert os.system('bash -c "gsettings set org.gnome.desktop.background draw-background true"') == 0
AssertionError

nots@pandemonium ~/.config/systemd/user $ gsettings set org.gnome.desktop.background draw-background true
No such key “draw-background”
nots@pandemonium ~/.config/systemd/user $ echo $DESKTOP_SESSION
ubuntu
```
